server:
  port: 8085

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/paymentdb}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ecommerce.payment: DEBUG
