package com.ecommerce.catalog.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * MongoDB document representing a product in the catalog.
 *
 * <p>Stored in the "products" collection. Indexed on {@code name} and
 * {@code category} to support efficient lookup and browsing queries.</p>
 */
@Document(collection = "products")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product {

    /**
     * Unique identifier generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * Human-readable product name; indexed for fast name-based searches.
     */
    @Indexed
    private String name;

    /**
     * Detailed description of the product.
     */
    private String description;

    /**
     * Selling price of the product (must be a positive value).
     */
    private Double price;

    /**
     * Product category; indexed to support category-based browsing.
     */
    @Indexed
    private String category;

    /**
     * Number of units currently available in inventory.
     */
    private Integer stock;

    /**
     * Identifier of the seller who owns this listing.
     */
    private String sellerId;

    /**
     * Whether this product is visible and purchasable on the platform.
     */
    @Builder.Default
    private boolean active = true;

    /**
     * Timestamp when the product record was first created.
     * Automatically populated by MongoDB auditing.
     */
    @CreatedDate
    private LocalDateTime createdAt;

    /**
     * Timestamp of the most recent update to this record.
     * Automatically populated by MongoDB auditing.
     */
    @LastModifiedDate
    private LocalDateTime updatedAt;
}
