name: Trigger auto deployment for payment-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo. 
  # Your payment-service-cicd.yml already builds and pushes the image to Docker Hub.
  # This workflow simply tells Azure to pull and redeploy that new image.
  push:
    branches: 
      [ main ]
    paths:
    - 'payment-service/**'
    - '.github/workflows/payment-service-AutoDeployTrigger-93a93db5-91da-4561-bd7e-c84d886e2a62.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PAYMENTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PAYMENTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PAYMENTSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy pre-built Docker Hub image to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: payment-service
          resourceGroup: rg-ecommerce-ctse
          imageToDeploy: docker.io/janukshan/ecommerce-payment-service:latest
          registryUrl: docker.io
          registryUsername: ${{ secrets.PAYMENTSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PAYMENTSERVICE_REGISTRY_PASSWORD }}


